### PR TITLE
47 wallet address functionality

### PR DESCRIPTION
**Pull request by Lyncis**
Solves everything from #47 
Full wallet address on hover:

screen shot 2018-09-04 at 2 00 47 pm

Transaction id on hover:

screen shot 2018-09-06 at 9 18 58 am

When user presses "Copy", wallet address is copied to the clipboard and message "Copied" is displayed for 2 seconds on the top:

screen shot 2018-09-06 at 9 19 36 am

### CODE REVIEW

**Comment by Lyncis** [comment]
Resolved the conflicts

**Comment by shawnlauzon** [comment]
@Lyncis These mockups look quite different from the designs [here](https://xd.adobe.com/view/2fe034a0-87f8-40a1-7bd6-9d82563a4d76-59d1/screen/0e1652ad-e20f-4c63-8aa0-29acd6baf28f/Wallet-after-clicking-Copy-wallet-address?fullscreen). Were you having problems? Did you talk with @Mojganahk ?

**Comment by Lyncis** [comment]
@shawnlauzon my bad, I missed the mockup for the toast. I'll change it now
But there are no mockups for the hover on the wallet address or transaction. Is that correct?

**Comment by shawnlauzon** [comment]
There are.

image

**Comment by Lyncis** [comment]
I'll fix it right now

**Comment by Lyncis** [comment]
Fixed styles
screen shot 2018-09-06 at 10 26 02 am
screen shot 2018-09-06 at 10 32 11 am
screen shot 2018-09-06 at 10 35 09 am

**Comment by shawnlauzon** [comment]
The hover should be a [tooltip](https://buefy.github.io/#/documentation/tooltip)

**Comment by Lyncis** [comment]
@shawnlauzon 
Wallet tooltip:
screen shot 2018-09-11 at 12 08 48 pm
Toast on a copy action:
screen shot 2018-09-11 at 12 08 51 pm
Transaction id tooltip
screen shot 2018-09-11 at 12 08 57 pm

**Pull request merged**
