### PR TITLE
44 wallet main screen top

### PR DESCRIPTION
**Pull request by omarodev**

### CODE REVIEW

**Comment by omarodev** [comment]
Wallet Main Top Screen design was done. Copied button and QR code are not working properly but they will be fixed in next PR for 46, 47, 48 issues

**Comment by shawnlauzon** [comment]
@omarodev Please resolve merge conflicts

**Comment by omarodev** [comment]
Yeah, I will remove conflicts soon.

**Comment by omarodev** [comment]
Conflicts were removed @shawnlauzon

**Pull request merged**
